### ISSUE TITLE
"Stack size exceeded" error

### ISSUE THREAD

**Issue by AirHans** [mohsen1/fb-photo-fetch#15]
Hello, I'm having this error. Any advice how to fix it please? Thanks.

`RangeError: Maximum call stack size exceeded
    at normalizeStringWin32 (path.js:33:30)
    at Object.resolve (path.js:328:20)
    at sync (C:\Users\Hans\Desktop\fb-photo-fetch-master\node_modules\mkdirp\index.js:68:14)
    at sync (C:\Users\Hans\Desktop\fb-photo-fetch-master\node_modules\mkdirp\index.js:77:24)
    at sync (C:\Users\Hans\Desktop\fb-photo-fetch-master\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\Hans\Desktop\fb-photo-fetch-master\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\Hans\Desktop\fb-photo-fetch-master\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\Hans\Desktop\fb-photo-fetch-master\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\Hans\Desktop\fb-photo-fetch-master\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\Hans\Desktop\fb-photo-fetch-master\node_modules\mkdirp\index.js:78:17)`

**Comment by mohsen1** [comment]
We are trying to make a folder on disk based on your Facebook phot album name. I'm guessing you have an album that has some sort of weird character in it. Can you guess which album that is?
