### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by robertgranholm** [mohsen1/fb-photo-fetch#16]
Hi, I'm new to this, but receiving this error...

Thanks : )

Error: Cannot find module '/Users/rgranholm/Desktop/fb-photo-fetch-master/index.js--tagged=true--dest=/Users/rgranholm/Pictures/Facebook_Photos--debug=api,json,download --token=THETOKEN'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
RFG-MbProR15T:fb-photo-fetch-master rgranholm$

**Comment by mohsen1** [comment]
You're probably missing a space after `index.js` in your command

**Comment by robertgranholm** [comment]
That got me a step further... new error

Error: Cannot find module 'minimist'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/rgranholm/Documents/GitHub/fb-photo-fetch/index.js:4:12)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
RFG-MbProR15T:fb-photo-fetch rgranholm$

**Comment by mohsen1** [comment]
Do a npm install

**Comment by robertgranholm** [comment]
I did an install, both versions listed below...throw error. Thank you so much for this help.

Last login: Thu Aug  2 11:30:02 on ttys002
RFG-MbProR15T:fb-photo-fetch rgranholm$ node -v
v8.11.3
RFG-MbProR15T:fb-photo-fetch rgranholm$ npm -v
5.6.0
RFG-MbProR15T:fb-photo-fetch rgranholm$ node index.js --tagged=true--dest=/Users/rgranholm/Desktop/Facebook_Photos--debug=api,json,download\ --token=EAAAASIRoIPABAGtbVcNGKDyN3UsbXe4PSEvixKooQk02JTIwWRwW9Uz0WZClE6y7iRfqZBMeh4yjhcJamo3mrIFivorRvwkUX7GLQLcqwNmspAQeCs4RbJHJQKFy1bpZAOW00wPtNKO0endroZAz6EzyiZCw3hT7vrsZBRepA1ej20RTq1Cpim8CLQVGnWp5Xg1qpn8fJFWAZDZD
module.js:549
    throw err;
    ^

Error: Cannot find module 'minimist'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/rgranholm/Documents/GitHub/fb-photo-fetch/index.js:4:12)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
RFG-MbProR15T:fb-photo-fetch rgranholm$
