### ISSUE TITLE
Error: undefined is not a valid uri or options object.

### ISSUE THREAD

**Issue by garyvdm** [mohsen1/fb-photo-fetch#8]
When trying to use this tool, I got this error:

```
/tmp/fb-photo-fetch/node_modules/request/index.js:44
    throw new Error('undefined is not a valid uri or options object.')
    ^

Error: undefined is not a valid uri or options object.
    at request (/tmp/fb-photo-fetch/node_modules/request/index.js:44:11)
    at /tmp/fb-photo-fetch/download.js:38:11
    at FSReqWrap.oncomplete (fs.js:170:21)
```

Output of  `npm ls`

```
fb-photo-fetch@1.0.0 /tmp/fb-photo-fetch
├── async@1.5.2
├─┬ debug@2.6.9
│ └── ms@2.0.0
├── minimist@1.2.0
├─┬ mkdirp@0.5.1
│ └── minimist@0.0.8
├── moment@2.22.0
├── piexifjs@1.0.3
├─┬ request@2.85.0
│ ├── aws-sign2@0.7.0
│ ├── aws4@1.6.0
│ ├── caseless@0.12.0
│ ├─┬ combined-stream@1.0.6
│ │ └── delayed-stream@1.0.0
│ ├── extend@3.0.1
│ ├── forever-agent@0.6.1
│ ├─┬ form-data@2.3.2
│ │ ├── asynckit@0.4.0
│ │ ├── combined-stream@1.0.6 deduped
│ │ └── mime-types@2.1.18 deduped
│ ├─┬ har-validator@5.0.3
│ │ ├─┬ ajv@5.5.2
│ │ │ ├── co@4.6.0
│ │ │ ├── fast-deep-equal@1.1.0
│ │ │ ├── fast-json-stable-stringify@2.0.0
│ │ │ └── json-schema-traverse@0.3.1
│ │ └── har-schema@2.0.0
│ ├─┬ hawk@6.0.2
│ │ ├─┬ boom@4.3.1
│ │ │ └── hoek@4.2.1 deduped
│ │ ├─┬ cryptiles@3.1.2
│ │ │ └─┬ boom@5.2.0
│ │ │   └── hoek@4.2.1 deduped
│ │ ├── hoek@4.2.1
│ │ └─┬ sntp@2.1.0
│ │   └── hoek@4.2.1 deduped
│ ├─┬ http-signature@1.2.0
│ │ ├── assert-plus@1.0.0
│ │ ├─┬ jsprim@1.4.1
│ │ │ ├── assert-plus@1.0.0 deduped
│ │ │ ├── extsprintf@1.3.0
│ │ │ ├── json-schema@0.2.3
│ │ │ └─┬ verror@1.10.0
│ │ │   ├── assert-plus@1.0.0 deduped
│ │ │   ├── core-util-is@1.0.2
│ │ │   └── extsprintf@1.3.0 deduped
│ │ └─┬ sshpk@1.14.1
│ │   ├── asn1@0.2.3
│ │   ├── assert-plus@1.0.0 deduped
│ │   ├─┬ bcrypt-pbkdf@1.0.1
│ │   │ └── tweetnacl@0.14.5 deduped
│ │   ├─┬ dashdash@1.14.1
│ │   │ └── assert-plus@1.0.0 deduped
│ │   ├─┬ ecc-jsbn@0.1.1
│ │   │ └── jsbn@0.1.1 deduped
│ │   ├─┬ getpass@0.1.7
│ │   │ └── assert-plus@1.0.0 deduped
│ │   ├── jsbn@0.1.1
│ │   └── tweetnacl@0.14.5
│ ├── is-typedarray@1.0.0
│ ├── isstream@0.1.2
│ ├── json-stringify-safe@5.0.1
│ ├─┬ mime-types@2.1.18
│ │ └── mime-db@1.33.0
│ ├── oauth-sign@0.8.2
│ ├── performance-now@2.1.0
│ ├── qs@6.5.1
│ ├── safe-buffer@5.1.1
│ ├── stringstream@0.0.5
│ ├─┬ tough-cookie@2.3.4
│ │ └── punycode@1.4.1
│ ├─┬ tunnel-agent@0.6.0
│ │ └── safe-buffer@5.1.1 deduped
│ └── uuid@3.2.1
├─┬ stream-to-buffer@0.1.0
│ └── stream-to@0.2.2
├── to-exif-date@1.0.0
└─┬ touch@0.0.3
  └─┬ nopt@1.0.10
    └── abbrev@1.1.1
```

**Comment by garyvdm** [comment]
Great. Thanks.
